import colorama
from colorama import Fore, Style
colorama.init(autoreset=True)
import time



def packtEncrypt_graphics():
    print("\n")
    print(             "                                   ________   ")
    time.sleep(0.07)
    print(             "                                  | _____ |\  ")
    time.sleep(0.07)
    print(Fore.GREEN + "                  _______________"+Fore.RESET+" | D____ |_\ ")
    time.sleep(0.07)
    print(Fore.GREEN + "                 / ______________|"+Fore.RESET+"| A_______ |")
    time.sleep(0.07)
    print(Fore.GREEN + "                / /               "+Fore.RESET+"| T_______ |")
    time.sleep(0.07)
    print(Fore.GREEN + "              __||__              "+Fore.RESET+"| A_______ |")
    time.sleep(0.07)
    print(Fore.GREEN + "              \    /              "+Fore.RESET+"|__________|")
    time.sleep(0.07)
    print(Fore.YELLOW+ "  ________"+Fore.RESET+ Fore.GREEN +"     \  /                            ")
    time.sleep(0.07)
    print(Fore.YELLOW+ " |\ ______\_____"+Fore.RESET+Fore.GREEN+"\/"+Fore.RESET+Fore.YELLOW+"___                          ")
    time.sleep(0.07)
    print(Fore.YELLOW+ " | |                 |                         ")
    time.sleep(0.07)
    print(Fore.YELLOW+ " | |                 |                         ")
    time.sleep(0.07)
    print(Fore.YELLOW+ " | |                 |                         ")
    time.sleep(0.07)
    print(Fore.YELLOW+ " | |     "+Fore.MAGENTA+"PACKET"+Fore.RESET+Fore.YELLOW+"      |                         ")
    time.sleep(0.07)
    print(Fore.YELLOW+ " | |  "+Fore.BLUE+" __________"+Fore.RESET+Fore.YELLOW+"    |                         ")
    time.sleep(0.07)
    print(Fore.YELLOW+ " |_|  "+Fore.BLUE+"|  ______  |"+Fore.RESET+Fore.YELLOW+"   |                         ")
    time.sleep(0.07)
    print(Fore.YELLOW+ "  \|__"+Fore.BLUE+"|_|"+Fore.RESET+Fore.YELLOW+"______"+Fore.RESET+Fore.BLUE+"|_|"+Fore.RESET+Fore.YELLOW+"___|                         ")
    time.sleep(0.07)
    print("\n\n")




def packtDecrypt_graphics():
    print("\n")
    print(Fore.GREEN+"                ______________________        ")
    time.sleep(0.07)
    print(Fore.GREEN+"               |  ___________________ \       ")
    time.sleep(0.07)
    print(Fore.GREEN+"               | |                   \ \      ")
    time.sleep(0.07)
    print(Fore.GREEN+"               | |                  __||__    ")
    time.sleep(0.07)
    print(Fore.GREEN+"               | |                  \    /    ")
    time.sleep(0.07)
    print(Fore.YELLOW+"  ________     "+Fore.RESET+Fore.GREEN+"| |                   \  /     ")
    time.sleep(0.07)
    print(Fore.YELLOW+" |\ ______\____"+Fore.RESET+Fore.GREEN+"|_|"+Fore.RESET+Fore.YELLOW+"___             "+Fore.RESET+" ___"+Fore.RESET+Fore.GREEN+"\/"+Fore.RESET+"__    ")
    time.sleep(0.07)
    print(Fore.YELLOW+" | |                 |            "+Fore.RESET+"| _____ |\  ")
    time.sleep(0.07)
    print(Fore.YELLOW+" | |                 |            "+Fore.RESET+"| D____ |_\ ")
    time.sleep(0.07)
    print(Fore.YELLOW+" | |                 |            "+Fore.RESET+"| A_______ |")
    time.sleep(0.07)
    print(Fore.YELLOW+" | |     "+Fore.RESET+Fore.MAGENTA+"PACKET"+Fore.RESET+Fore.YELLOW+"      |            "+Fore.RESET+"| T_______ |")
    time.sleep(0.07)
    print(Fore.YELLOW+" | |   "+Fore.RESET+Fore.BLUE+"__________ "+Fore.RESET+Fore.YELLOW+"   |            "+Fore.RESET+"| A_______ |")
    time.sleep(0.07)
    print(Fore.YELLOW+" |_|  "+Fore.RESET+Fore.BLUE+"|  ______  |"+Fore.RESET+Fore.YELLOW+"   |            "+Fore.RESET+"|__________|")
    time.sleep(0.07)
    print(Fore.YELLOW+"  \|__"+Fore.RESET+Fore.BLUE+"|_|"+Fore.RESET+Fore.YELLOW+"______"+Fore.RESET+Fore.BLUE+"|_|"+Fore.RESET+Fore.YELLOW+"___|                        ")
    time.sleep(0.07)
    print("\n\n")



def key_graphics(width):
    print(Style.BRIGHT+Fore.GREEN+"                                     ________     ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.GREEN+"                                    / ______ \    ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.GREEN+" __________________________________/ |      | \   ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.GREEN+"/____________________________________|      |  |  ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.GREEN+"\__     __  __     ________________  |      |  |  ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.GREEN+"   \ | /  \/  \ | /                \ |______| /   ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.GREEN+"    |||        |||                  \________/    ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.GREEN+"    /|\        /|\                                ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.GREEN+"    \_/        \┴/                                ".center(width))
    time.sleep(0.07)
    print("\n\n")
    

def lock(width):
    print("\n")
    print(Style.BRIGHT+Fore.YELLOW+"              ******           ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.YELLOW+"         ***         ***        ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.YELLOW+"      ((*               *))     ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.YELLOW+"    ((*                   *))  ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.YELLOW+"    ▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄  ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.YELLOW+"    ▓                       ▓  ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.YELLOW+"    ▓                       ▓  ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.YELLOW+"    ▓                       ▓  ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.YELLOW+"    ▓          (*)          ▓  ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.YELLOW+"    ▓          | |          ▓  ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.YELLOW+"    ▓          |_|          ▓  ".center(width))
    time.sleep(0.07)
    print(Style.BRIGHT+Fore.YELLOW+"    ▓▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▓  ".center(width))
    print()


def banner():
    print()
    print(Fore.MAGENTA+"███████╗████████╗███████╗ ██████╗               ███████╗".center(150))
    print(Fore.MAGENTA+"██╔════╝╚══██╔══╝██╔════╝██╔════╝               ██╔════╝".center(150))
    print(Fore.MAGENTA+"███████╗   ██║   █████╗  ██║  ███╗    █████╗    █████╗  ".center(150))
    print(Fore.MAGENTA+"╚════██║   ██║   ██╔══╝  ██║   ██║    ╚════╝    ██╔══╝  ".center(150))
    print(Fore.MAGENTA+"███████║   ██║   ███████╗╚██████╔╝              ███████╗".center(150))
    print(Fore.MAGENTA+"╚══════╝   ╚═╝   ╚══════╝ ╚═════╝               ╚══════╝".center(150))
    print(Fore.BLUE+Style.BRIGHT+"                                                  Tool By: -".center(150))
    print(Fore.BLUE+Style.BRIGHT+"                                                                                    ashchaubey, cptn3m0grv,".center(150))
    print(Fore.BLUE+Style.BRIGHT+"                                                                                    Dracula62,  Stalwart-GS".center(150))