import platform

def manual_page():    
    if("Windows" in platform.platform()):
        print('\n')
        print('For About Page:')
        print('\tpython steg-e.py about')
        print('\n')
        print('For Encryption:')
        print('\tpython steg-e.py encrypt -c <path_of_carrier_file> -d <path_of_message_file> -r <path_of_result_file>')
        print('\tpython steg-e.py encrypt --carrier <path_of_carrier_file> --data <path_of_message_file> --result <path_of_result_file>')
        print('\n')
        print('For Decryption:')
        print('\tpython steg-e.py decrypt -r <path_of_result_file>')
        print('\tpython steg-e.py decrypt --result <path_of_result_file>')
        print('\n')
        print('For Packet Encryption:')
        print('\tpython steg-e.py packetEncrypt -d <path_of_message_file> -r <path_of_result_file>')
        print('\tpython steg-e.py packetEncrypt --data <path_of_message_file> --result <path_of_result_file>')
        print('\n')
        print('For Packet Decryption:')
        print('\tpython steg-e.py packetDecrypt -r <path_of_result_file>')
        print('\tpython steg-e.py packetDecrypt --result <path_of_result_file>')

    else:
        print('\n')
        print('For About Page:')
        print('\tpython3 steg-e.py about')
        print('\n')
        print('For Encryption:')
        print('\tpython3 steg-e.py encrypt -c <path_of_carrier_file> -d <path_of_message_file> -r <path_of_result_file>')
        print('\tpython3 steg-e.py encrypt --carrier <path_of_carrier_file> --data <path_of_message_file> --result <path_of_result_file>')
        print('\n')
        print('For Decryption:')
        print('\tpython3 steg-e.py decrypt -r <path_of_result_file>')
        print('\tpython3 steg-e.py decrypt --result <path_of_result_file>')
        print('\n')
        print('For Packet Encryption:')
        print('\tpython3 steg-e.py packetEncrypt -d <path_of_message_file> -r <path_of_result_file>')
        print('\tpython3 steg-e.py packetEncrypt --data <path_of_message_file> --result <path_of_result_file>')
        print('\n')
        print('For Packet Decryption:')
        print('\tpython3 steg-e.py packetDecrypt -r <path_of_result_file>')
        print('\tpython3 steg-e.py packetDecrypt --result <path_of_result_file>')